#!/usr/bin/env python

import sys
import time

import dmenu
import intern.cloud

vms = intern.cloud.find()
names = [vm.name for vm in vms]
name = dmenu.dmenu(names)

if not name:
    sys.exit(1)

print 'killing VMs named %s' % name

for vm in vms:
    if vm.name == name:
        print vm.delete()

time.sleep(0.5)
